# Copyright 2026 Google LLC
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

from collections import defaultdict, namedtuple
from datetime import datetime
import sys
# to generate nccl_telemetry_proto_pb2.py:
# download and install protobuf from protobuf.dev/downloads/
# protoc --proto_path=$PWD --python_out=$PWD nccl_telemetry_proto.proto
import nccl_telemetry_proto_pb2
import pandas as pd

DistType = nccl_telemetry_proto_pb2.DistType
ncclStatsConnectionType = nccl_telemetry_proto_pb2.ncclStatsConnectionType

ConnectionData = namedtuple(
    "ConnectionData", ["time_stamp", "counts", "bounds", "min", "max", "avg"]
)

# Types of distributions/histograms we expect
DIST_TYPE_LABELS = {
    # Generated by all GPUViz versions.
    DistType.protoSendLatencySW: "Software Send Latency",
    DistType.protoRecvLatencySW: "Software Receive Latency",
    DistType.protoSendLatencyNetHW: "Network Hardware Send Latency",
    DistType.protoRecvLatencyNetHW: "Network Hardware Receive Latency",
    DistType.protoRecvReadylatency: "Receive Ready Latency",
    DistType.protoSendMessageSize: "Send Message Size",
    DistType.protoRecvMessageSize: "Receive Message Size",
    # Generated by GPUViz versions released on or after 2024/10/17 ONLY
    # when BW collection flag (i.e. NCCL_GPUVIZ_BANDWIDTH_HISTOGRAM_COLLECTION_ENABLE) is enabled.).
    DistType.protoSendBandwidth: "High Frequency Send Bandwidth",
    DistType.protoRecvBandwidth: "High Frequency Recv Bandwidth",
}


# The string concatenation of local and remote end-point is used as key to store data for a particular connection in a dictionary.
def get_connection_name(conn):
  local_extra = ""
  remote_extra = ""
  conn_type = conn.connection_id.connection.conn_type
  if conn_type == ncclStatsConnectionType.EntityNVLConnection:
    # TODO
    return ""
  elif conn_type == ncclStatsConnectionType.EntityPCIConnection:
    # TODO
    return ""
  elif conn_type == ncclStatsConnectionType.EntityTCPConnection:
    connection = conn.connection_id.connection.tcp_conn
  elif conn_type == ncclStatsConnectionType.EntityRDMAConnection:
    connection = conn.connection_id.connection.rdma_conn
    local_extra = ":qp:" + str(connection.local_qpn)
    remote_extra = ":qp:" + str(connection.remote_qpn)
  else:
    # TODO
    return ""
  return (
      connection.local_endpoint
      + local_extra
      + "_"
      + connection.remote_endpoint
      + remote_extra
  )


# Prints all connection identifier data.
def print_conn_id(conn):
  print(
      "================== Connection Identification Information"
      " ========================="
  )
  conn_id = conn.connection_id
  print("Network plug in name:", conn_id.nccl_plugin_name)
  print("GPU PCI ADDR:", conn_id.gpu_pci_addr)
  print("Connection local and remote addresses:", get_connection_name(conn))
  print("Time Stamp:", datetime.fromtimestamp(conn.time_stamp.seconds))
  print("================== End Information =========================")


def print_conn_data(name, dist_type, conn_data):
  print(f"Connection: {name}")
  print(f"Metric: {DIST_TYPE_LABELS[dist_type]}")
  print(f"Time Stamp: {conn_data.time_stamp}")
  print("Other stats since last reported:")
  print(f"Min: {conn_data.min}")
  print(f"Max: {conn_data.max}")
  print(f"Avg: {conn_data.avg}")
  print(f"Measurements in Histogram:")
  lower_bound = 0
  for count, upper_bound in zip(conn_data.counts, conn_data.bounds):
    print(f"{lower_bound:.4f}...{upper_bound:.4f} : {count}")
    lower_bound = upper_bound


# For the given connection add data for current time-stamp.
def process_connection_data_point(conn, conn_bytes):
  name = get_connection_name(conn)
  print_conn_id(conn)
  for hist in conn.histogram:
    max_bucket = hist.max_bucket
    base = hist.base
    scale = hist.scale_factor
    new_data = ConnectionData(
        conn.time_stamp.seconds + conn.time_stamp.nanos / 10**9,
        [curr for curr in hist.bucket_counts],
        [(base**i) * scale for i in range(len(hist.bucket_counts))],
        hist.min,
        hist.max,
        hist.avg,
    )
    if new_data.bounds[-1] >= hist.max_bucket:
      new_data.bounds[-1] = float("inf")

    if hist.dist_type == DistType.protoSendMessageSize:
      conn_bytes[name][0] += sum(new_data.counts) * hist.avg
    if hist.dist_type == DistType.protoRecvMessageSize:
      conn_bytes[name][1] += sum(new_data.counts) * hist.avg
    print_conn_data(name, hist.dist_type, new_data)


def parse_data(data):
  all_stats = nccl_telemetry_proto_pb2.AllStats()
  delimiter = b"==END=="

  # The last item is either an empty string or a partially written protobuf
  # serialization.
  messages = data.split(delimiter)[:-1]
  conn_byte_totals = defaultdict(lambda: [0, 0])
  for msg_data in messages:
    try:
      all_stats.ParseFromString(msg_data)
      for conn in all_stats.conn_stats:
        process_connection_data_point(conn, conn_byte_totals)
    except:
      pass

  df = pd.DataFrame.from_dict(
      conn_byte_totals, orient="index", columns=["Bytes Sent", "Bytes Received"]
  )
  if not df.empty:
    print(
        "================== Bytes Send and Received ========================="
    )
    df.rename_axis("Connection", inplace=True)
    print(df)
    print("================== End Information =========================")


def read_data(fname):
  data = open(fname, "rb").read()
  parse_data(data)


if __name__ == "__main__":
  read_data(sys.argv[1])
